### ISSUE TITLE
Allow environment variables to be overridden

### ISSUE THREAD

**Issue by AtomBaf** [picoCTF/oci-interceptor#27]
Hi
Seems that I finally found something for my use-case with your project!

Use-case:
I create docker images which are agnostic of where they will be run. Depending on their final running location, environment variables might be different. Today, I'm forced to start the containers with the right options needed for the right environment.

Looking for a solution, I had the idea that the environment variables should be set once for a given host, and then all running containers might inherit these variables. But unfortunately with docker I did not find any way to do it (only the [proxy settings](https://docs.docker.com/network/proxy/) could be set)

I then searched in the OCI and container runtime things and finally found your project. This seems exactly what I need for my use case.

So could you please tell me first if I'm right? and then if true, do you see ans interest of implementing this behavior (overriding env variables)?

Many thanks

**Comment by dmartin** [comment]
Hi, sorry for the delay in getting back to you. I do think that adding the ability to set default environment variable fallbacks for containers would be an interesting addition to this project. It definitely falls in line with the general idea of "working around Docker daemon limitations".

It's similar to another feature I had in mind (setting default resource constraints) so I may be able to address both at once once we get around to it.

**Comment by AtomBaf** [comment]
sounds great, and also for the contraints feature... will definitely enjoy it.
Let me know of you need testing or any kind of contribution.

**Comment by AtomBaf** [comment]
👍
